version: '3.7'
services:
  redis:
    image: redis:7.0.10-alpine
    container_name: redis
    restart: unless-stopped
    network_mode: bridge
    # expose:
    #   - 6379

  api:
    build: .
    container_name: api
    restart: unless-stopped
    network_mode: bridge
    command: /bin/sh -c 'nodemon -e js,html index.js'
    ports:
      - 8083:9000
    volumes:
      - .:/src
      - /src/node_modules   #local directory에서 빈 node_modules가 컨테이너의 node_modules를 덮어쓰지 않도록 하는 역할 -> anonymous volume hack이라고 불림.
    # environment:
    #   NODE_ENV: dev
    #   REDIS_URL: redis://cache
    links:
      - redis   # 이것이 있어야 redis에 접속 가능
